#include "hal_data.h"
#include "Motor_Control.h"
#include "DHT11.h"
#include "Chao_Sheng_Bo.h"
#include <stdio.h>
#include <string.h>



bsp_io_level_t Hong_Wai_Pin;//红外状态存放引脚，0为有遮挡，1为没有遮挡

#define Hong_Wai_Du_Qu() R_IOPORT_PinRead(&g_ioport_ctrl, BSP_IO_PORT_07_PIN_08, &Hong_Wai_Pin);//读取红外状态

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
 
 
void hal_entry(void)
{
	R_IOPORT_Open(&g_ioport_ctrl, g_ioport.p_cfg);//初始化配置引脚，加载瑞萨 RA 配置工具（FSP Configurator）里配置的所有引脚模式

    /* TODO: 在此处添加你的代码 */
	
	float Ju_Li = 0;  // 每次超声波采集的距离
	float Sum = 0;   // 5次超声波采集距离的总和
	float Mean = 0; // 取平均数使结果更准确
	uint8_t uart_buf[50] = {0}; // 串口发送代码的存放字符串的数组
	
//	Motor_PWM_Init();//电机初始化
//	DHT11_Read();//读取DHT11温湿度数据并校验
//	
//	Motor_Left_Speed(75);//左电机速度
//	Motor_Right_Speed(75);//右电机速度

	UART0_Init(); // 串口初始化
	Chao_Sheng_Bo_GPT0_Init(); // 超声波初始化
	
	while(1)
	{
		Ju_Li = 0;  // 每次超声波采集的距离
		Sum = 0;   // 5次超声波采集距离的总和
		Mean = 0; // 取平均数使结果更准确
		for(int i = 0; i < 5 ; i++)
		{
			Ju_Li = HC_SR04_Measure(); // 超声波测距采集
			// 过滤0值，确保累加有效距离
			if(Ju_Li > 0) 
			{
				Sum += Ju_Li;
			}
			else
			{
				i--; // 重新采集一次
			}
			
			R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS); // 50ms 一采集
		}
		Mean = Sum / 5;
		sprintf((char *)uart_buf,"Ju_Li=%.2f",Mean);
		uint16_t send_len = (uint16_t)strlen((char *)uart_buf);
		R_SCI_UART_Write(&g_uart0_ctrl,uart_buf,send_len);
		R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MILLISECONDS);
		Hong_Wai_Du_Qu();//读取红外传感器的状态
		if(Hong_Wai_Pin == 1)//如果没有遮挡则启动电机，1为没有遮挡，0为有遮挡
		{
			// 前进1秒：拆分为10ms×100次，每次检测红外
			for(int i=0; i<100; i++)
			{
				Hong_Wai_Du_Qu();
				if(Hong_Wai_Pin == 0) break; // 红外有遮挡，立即停止
				Car_Forward();
				R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
			}
			for(int i=0; i<92; i++)
			{
				Hong_Wai_Du_Qu();
				if(Hong_Wai_Pin == 0) break; // 红外有遮挡，立即停止
				Car_Turn_L();//小车左转
				R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
			}
			for(int i=0; i<70; i++)
			{
				Hong_Wai_Du_Qu();
				if(Hong_Wai_Pin == 0) break; // 红外有遮挡，立即停止
				Car_Forward();//小车前进
				R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
			}
			Car_Stop();//小车停止
		}
		else
		{
			Car_Stop();//小车停止
		}
	}
	
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

